spring.jpa.database=postgresql
spring.sql.init.platform=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://silly.db.elephantsql.com/acujtons
spring.datasource.username=acujtons
spring.datasource.password=GnL1heLCALIea6NhUWV63xg8IVg_W9Gd
spring.datasource.hikari.maximum-pool-size=2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
